### ISSUE TITLE
I know how to use detectnet in detecting object.But how can I write the code,I want to use it in my own code.

### ISSUE THREAD

**Issue by yangrisheng** [dusty-nv/jetson-inference#1215] opened 2021-09-07 10:19 UTC
I know how to use detectnet in detecting object.But how can I write the code,I want to use it in my own code.I want to combine road following and object detection?How can I do?

**Comment by dusty-nv** [comment] 2021-09-07 19:14
Closing as duplicate of https://github.com/dusty-nv/jetson-inference/issues/1216

**Closed by dusty-nv** 2021-09-07 19:14 UTC
